services:
  playwright-test:
    image: playwright-test:v1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./test-data:/app/test-data
      - ./playwright-report/:/app/playwright-report
      - ./test-results/:/app/test-results
      - ./.env:/app/.env
    environment:
      - DISPLAY=:99
    entrypoint: sh -c "Xvfb :99 & exec \"$@\""
    command: npm run test:pdf
